package com.andresinternship.linkedinclone.service;

import com.andresinternship.linkedinclone.model.Company;
import com.andresinternship.linkedinclone.model.User;
import com.andresinternship.linkedinclone.repository.CompanyRepository;
import com.andresinternship.linkedinclone.repository.UserRepository;
import com.andresinternship.linkedinclone.controller.dto.CompanyCreationRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Optional;
import java.util.UUID;

@Service
public class CompanyService {

    @Autowired
    private CompanyRepository companyRepository;

    @Autowired
    private UserRepository userRepository;

    public Company createCompany(CompanyCreationRequest companyCreationRequest) {
        Company company = new Company();
        // I think it can be directly generated by database with correct annotations in entity class.
        company.setCompany_id(UUID.randomUUID());
        company.setName(companyCreationRequest.getName());
        company.setDescription(companyCreationRequest.getDescription());

        String userEmail = tokenService.extractEmailFromToken(companyCreationRequest.getToken());
        Optional<User> owner = userRepository.findByEmail(userEmail);
        owner.ifPresent(user -> company.setOwner(user));

        companyRepository.save(company);
        return company;
    }
}
